export const UPDATE_SEARCH_TERM = 'UPDATE_SEARCH_TERM';
export const FETCH_NAVBAR_GENRES = 'FETCH_NAVBAR_GENRES';
export const FETCH_NAVBAR_GENRES_SUCCEEDED = 'FETCH_NAVBAR_GENRES_SUCCEEDED';
export const FETCH_NAVBAR_GENRES_FAILED = 'FETCH_NAVBAR_GENRES_FAILED';
