export const FETCH_SEARCH_MOVIES = 'FETCH_SEARCH_MOVIES';
export const FETCH_SEARCH_MOVIES_CANCEL = 'FETCH_SEARCH_MOVIES_CANCEL';
export const FETCH_SEARCH_MOVIES_SUCCEEDED = 'FETCH_SEARCH_MOVIES_SUCCEEDED';
export const FETCH_SEARCH_MOVIES_FAILED = 'FETCH_SEARCH_MOVIES_FAILED';