export const FETCH_MOVIES_WITH_GENRES = 'FETCH_MOVIES_WITH_GENRES';
export const FETCH_MOVIES_WITH_GENRES_SUCCEEDED = 'FETCH_MOVIES_WITH_GENRES_SUCCEEDED';
export const FETCH_MOVIES_WITH_GENRES_FAILED = 'FETCH_MOVIES_WITH_GENRES_FAILED';
