export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIES_SUCCEEDED = 'FETCH_MOVIES_SUCCEEDED';
export const FETCH_MOVIES_FAILED = 'FETCH_MOVIES_FAILED';
export const FETCH_LATEST_MOVIES = 'FETCH_LATEST_MOVIES';
export const FETCH_LATEST_MOVIES_SUCCEEDED = 'FETCH_LATEST_MOVIES_SUCCEEDED';
export const FETCH_LATEST_MOVIES_FAILED = 'FETCH_LATEST_MOVIES_FAILED';
