export const FETCH_USER_PROFILE = 'FETCH_USER_PROFILE';
export const FETCH_USER_PROFILE_SUCCEEDED = 'FETCH_USER_PROFILE_SUCCEEDED';
export const FETCH_USER_PROFILE_FAILED = 'FETCH_USER_PROFILE_FAILED';
