export const FETCH_USER_INIT_APP = 'FETCH_USER_INIT_APP';
export const FETCH_USER_INIT_APP_SUCCEEDED = 'FETCH_USER_INIT_APP_SUCCEED`ED';
export const FETCH_USER_INIT_APP_FAILED = 'FETCH_USER_INIT_APP_FAILED';

export const FETCH_USER_PROFILE = 'FETCH_USER_PROFILE';
export const FETCH_USER_PROFILE_SUCCEEDED = 'FETCH_USER_PROFILE_SUCCEEDED';
export const FETCH_USER_PROFILE_FAILED = 'FETCH_USER_PROFILE_FAILED';

export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const UPDATE_USER_PROFILE_SUCCEEDED = 'UPDATE_USER_PROFILE_SUCCEEDED';
export const UPDATE_USER_PROFILE_FAILED = 'UPDATE_USER_PROFILE_FAILED';
